"""add user relationship to short_urls

Revision ID: 513ded310a14
Revises: cfd0250000f7
Create Date: 2026-07-17 13:34:56.165062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513ded310a14'
down_revision: Union[str, Sequence[str], None] = 'cfd0250000f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'short_urls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'short_urls', type_='foreignkey')
    op.drop_column('short_urls', 'user_id')
    # ### end Alembic commands ###
